"""add tickets and ticket_analysis

Revision ID: 48115a2cc771
Revises: fe56fa70289e
Create Date: 2026-03-31 20:56:55.377560

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '48115a2cc771'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('open', 'analyzing', 'resolved', 'escalated', name='ticketstatus'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticketanalysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('diagnosis', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('suggested_fix', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='ticketpriority'), nullable=False),
    sa.Column('needs_human', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticketanalysis')
    op.drop_table('ticket')
    # ### end Alembic commands ###
